site_name: 'DxE SF Bay Area Documents'
site_url: 'https://docs.dxesf.org/'

repo_name: 'dxe/dxesf-docs'
repo_url: 'https://github.com/dxe/dxesf-docs'

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'orange'
  font:
    text: 'Source Serif Pro'
  custom_dir: 'theme'

  # TODO(mdempsky): Set based on environment variable.
  draft: True

markdown_extensions:
  - footnotes
  - smarty
